export const merchantDetails = [
    {
        id: 1,
        name: "Zephyra Windrider",
        offerings: [
            { name: "Featherfall Brooch", description: "Prevents fall damage, allowing the wearer to drift safely to the ground.", price: "300 GP", availability: "Uncommon" },
            { name: "Gale Gauntlets", description: "Projects a blast of wind, pushing enemies or objects within 10 feet.", price: "500 GP", availability: "Rare" },
            { name: "Breeze Mantle", description: "Enhances agility; grants +2 Dexterity while worn.", price: "800 GP", availability: "Rare" },
            { name: "Cloak of Billowing", description: "A purely cosmetic cloak that billows dramatically on command.", price: "50 GP", availability: "Common" },
            { name: "Winged Boots", description: "Grants the ability to fly for up to 4 hours per day, in 1-hour increments.", price: "1,200 GP", availability: "Rare" },
            { name: "Windcaller's Flute", description: "Summons a gentle wind when played; can disperse smoke or light fog.", price: "250 GP", availability: "Uncommon" },
            { name: "Portable Glider", description: "Allows for safe gliding from great heights; reusable.", price: "400 GP", availability: "Uncommon" },
            { name: "Tempest Sphere", description: "A one-time-use item that unleashes a powerful gust in all directions.", price: "150 GP", availability: "Rare" },
            { name: "Storm Strider Sandals", description: "Doubles walking speed during storms or windy conditions.", price: "600 GP", availability: "Rare" },
            { name: "Sky Crystal Lantern", description: "A lantern that never extinguishes and glows like the morning sky.", price: "300 GP", availability: "Uncommon" },
            { name: "Zephyr Ring", description: "Grants resistance to lightning damage.", price: "700 GP", availability: "Rare" },
            { name: "Amulet of Weatherward", description: "Allows the wearer to predict weather 24 hours in advance.", price: "250 GP", availability: "Uncommon" },
            { name: "Whispering Feather", description: "Sends a message carried by the wind to a recipient within 1 mile.", price: "150 GP", availability: "Common" },
            { name: "Enchanted Parasol", description: "Shields the user from heavy rain and grants +1 AC.", price: "200 GP", availability: "Uncommon" },
            { name: "Cloudstep Charm", description: "Enables the wearer to walk on clouds as if they were solid ground.", price: "900 GP", availability: "Rare" },
            { name: "Windsong Dagger", description: "A light dagger that whistles when thrown, returning to the wielder's hand.", price: "1,000 GP", availability: "Very Rare" },
            { name: "Hurricane Pendant", description: "Once per day, summon a 10-foot-radius whirlwind for 1 minute.", price: "2,000 GP", availability: "Legendary" },
            { name: "Skyweaver Cloak", description: "Grants advantage on stealth checks in the air.", price: "750 GP", availability: "Rare" },
            { name: "Air Elemental Core", description: "A rare crafting material that hums with latent wind energy.", price: "1,500 GP", availability: "Very Rare" },
            { name: "Earring of the Breeze", description: "Grants +2 to perception checks related to sound or smell.", price: "300 GP", availability: "Uncommon" },
        ],
        specialOffers: "Discount for Stories: 10% off if you share a tale of adventure with Zephyra.",
        tradePolicy: "Accepts gold, silver, and trade for rare feathers, gemstones, or wind-related relics.",
        personalityTraits: ["Mysterious", "Eccentric"],
        quirks: ["Faint whispers of wind echo around her stall.", "Sometimes hums a haunting melody while organizing items."],
        catchphrases: ["The value of an item isn't just in gold—it's in the stories it carries.", "Trust me, this one's special."],
        disposition: "Friendly and curious, but distant with those who seem reckless or violent.",
        hooks: {
            rumors: "They say she once calmed a storm that threatened an entire fleet with just her voice.",
            sideQuest: "Recover a stolen Gale Stone, a rare artifact tied to her airship's navigation.",
            hiddenMotive: " Zephyra is a guardian of the elemental plane of air, sent to monitor disruptions between realms.",
        },
        token: "images/token/token1.png",
        shopDescription: "A small, mobile stall crafted from lightweight wood and silk, perched on the deck of her airship or atop a windswept mountain. The stall is adorned with wind chimes that tinkle softly in the breeze, and an enchanted banner that reads, “Zephyra's Wares - Only for Those Guided by the Winds.”",
        rulesOfTrade: "No refunds, unless the item fails to function as described.",
        hours: "Appears at dawn and departs before nightfall.",
        uniqueSellingPoint: "Zephyra specializes in items like the Featherfall Brooch (prevents fall damage), Gale Gauntlets (project wind blasts), and Breeze Mantle (enhances agility)."
    },

    {
        id: 2,
        name: "Grelthar Ironbite",
        offerings: [
            { name: "Adamantine Pickaxe of the Deep", description: "Reveals hidden veins of ore and grants +2 to mining-related checks.", price: "700 GP", availability: "Rare" },
            { name: "Shield of Resonance", description: "Reflects sound-based attacks back at the source; grants +2 AC.", price: "1,200 GP", availability: "Very Rare" },
            { name: "Volcanic Warhammer", description: "Deals an additional 1d6 fire damage on hit; ignites flammable objects.", price: "1,500 GP", availability: "Very Rare" },
            { name: "Dwarven Thrower (Hammer)", description: "Returns to the wielder's hand after being thrown; deals +3 damage to giants.", price: "3,000 GP", availability: "Legendary" },
            { name: "Forge Master's Apron", description: "Grants fire resistance and +2 to crafting-related checks.", price: "600 GP", availability: "Rare" },
            { name: "Molten Edge Battleaxe", description: "Can cleave through non-magical metal as if it were butter; deals +2 fire damage.", price: "1,400 GP", availability: "Rare" },
            { name: "Stoneseeker Amulet", description: "Grants tremorsense within 15 feet; perfect for underground navigation.", price: "900 GP", availability: "Rare" },
            { name: "Ironbite Crossbow", description: "Inflicts additional 1d8 piercing damage against armored foes.", price: "800 GP", availability: "Rare" },
            { name: "Emberforge Gauntlets", description: "Enhances unarmed strikes, adding 1d6 fire damage on hit.", price: "500 GP", availability: "Uncommon" },
            { name: "Runed Mining Lantern", description: "Illuminates dark areas within 30 feet and highlights minerals in its glow.", price: "250 GP", availability: "Common" },
            { name: "Ore Diviner's Pendant", description: "Pulses faintly when near precious metals or gemstones.", price: "300 GP", availability: "Uncommon" },
            { name: "Ringscribed Shield", description: "Grants +1 AC and resistance to one chosen damage type (set at forging).", price: "1,000 GP", availability: "Rare" },
            { name: "Stonebreaker Maul", description: "Deals double damage to stone objects and constructs.", price: "1,200 GP", availability: "Rare" },
            { name: "Diamond-Tipped Chisel", description: "Perfect for carving magical runes or fine stonework; increases precision.", price: "400 GP", availability: "Uncommon" },
            { name: "Deep Delver's Boots", description: "Prevents slipping and falling on rocky or uneven terrain.", price: "300 GP", availability: "Uncommon" },
            { name: "Hearthstone Amulet", description: "Once per day, grants temporary fire immunity for 1 minute.", price: "800 GP", availability: "Rare" },
            { name: "Anvil of Speed", description: "Speeds up crafting time by 25%; portable but heavy.", price: "1,000 GP", availability: "Rare" },
            { name: "Embersteel Greaves", description: "Reduces fire damage by half and grants +1 AC.", price: "700 GP", availability: "Rare" },
            { name: "Forgefire Powder", description: "A single-use item that creates an intense flame for crafting or combat.", price: "200 GP", availability: "Common" },
            { name: "Runescribed Hammer", description: "Grants +2 to smithing checks and allows engraving magical runes onto items.", price: "900 GP", availability: "Rare" }
        ],
        specialOffers: "Bulk Deals: Purchase three or more mining tools and receive a free Runed Mining Lantern.",
        tradePolicy: "Accepts gold, mithral ingots, and rare gemstones as payment.",
        personalityTraits: ["Gruff", "Proud of craftsmanship"],
        quirks: ["Often strokes his braided beard when thinking.", "Muttering in Dwarvish about smithing techniques."],
        catchphrases: ["You've come to the right place if you're after quality.", "Go on then, and don't let my work go to waste!"],
        disposition: "Respects skilled artisans and hardworking adventurers; impatient with those who seem wasteful or lazy.",
        hooks: {
            rumors: "They say Grelthar forged the weapon that felled a dragon, but he refuses to talk about it.",
            sideQuest: "Recover a stolen shipment of Embersteel ingots taken by a group of bandits.",
            hiddenMotive: "Grelthar is secretly crafting a legendary weapon to prepare for a looming Underdark threat."
        },
        token: "images/token/token2.png",
        shopDescription: "A sturdy forge built into a massive wagon, with glowing embers visible through iron vents. The air smells of smoke, molten metal, and determination, while racks of weapons and tools line the perimeter.",
        rulesOfTrade: "No refunds. If an item breaks, it's your fault, not Grelthar's.",
        hours: "Open from dawn to dusk, or until Grelthar decides it's time for a break.",
        uniqueSellingPoint: "Grelthar specializes in dwarven-forged weapons, armor, and mining equipment, with subtle runic engravings that glow faintly."
    },
    
    {
        id: 3,
        name: "Lumina Starshade",
        offerings: [
            { name: "Moonlit Orb", description: "Casts a protective light in darkness, granting +2 to saving throws against fear while active.", price: "400 GP", availability: "Uncommon" },
            { name: "Stargazer's Compass", description: "Always points to your heart's desire, even in magical darkness.", price: "1,000 GP", availability: "Rare" },
            { name: "Meteor Shard Dagger", description: "Deals an additional 1d6 radiant damage on hit and glows faintly.", price: "1,200 GP", availability: "Rare" },
            { name: "Celestial Mantle", description: "Grants advantage on stealth checks under starlight.", price: "800 GP", availability: "Rare" },
            { name: "Astral Band", description: "A ring that grants the wearer resistance to radiant damage.", price: "600 GP", availability: "Rare" },
            { name: "Comet Lantern", description: "A lantern that emits bright light in a 60-foot radius; can dispel magical darkness once per day.", price: "750 GP", availability: "Rare" },
            { name: "Starwoven Cloak", description: "Provides a +1 bonus to AC and grants resistance to cold damage.", price: "900 GP", availability: "Very Rare" },
            { name: "Nova Pearl", description: "A one-time-use item that creates a radiant explosion (6d6 damage, 30-foot radius).", price: "1,500 GP", availability: "Very Rare" },
            { name: "Lunar Bow", description: "Grants +2 to attack rolls during the night and fires radiant arrows.", price: "2,000 GP", availability: "Legendary" },
            { name: "Eclipse Pendant", description: "Once per day, creates an area of dim light that suppresses invisibility within 20 feet.", price: "1,200 GP", availability: "Rare" },
            { name: "Stardust Pouch", description: "A bag of magical stardust that can coat objects, making them shine brightly for 1 hour.", price: "300 GP", availability: "Common" },
            { name: "Cosmic Hourglass", description: "Allows the user to reverse time by 6 seconds once per day.", price: "2,500 GP", availability: "Legendary" },
            { name: "Aurora Blade", description: "A longsword that creates a radiant aurora when swung, dealing an additional 2d6 radiant damage.", price: "2,000 GP", availability: "Very Rare" },
            { name: "Lunar Lotus", description: "A flower that blooms only under moonlight; can be used as an ingredient in celestial potions.", price: "500 GP", availability: "Uncommon" },
            { name: "Celestial Globe", description: "Projects a detailed map of the night sky, including hidden constellations.", price: "700 GP", availability: "Rare" },
            { name: "Nebula Gauntlets", description: "Enhances spell attacks, granting +1 to hit and damage rolls for radiant-based spells.", price: "1,500 GP", availability: "Very Rare" },
            { name: "Falling Star Talisman", description: "Grants the ability to cast *Feather Fall* once per day.", price: "250 GP", availability: "Uncommon" },
            { name: "Starfire Elixir", description: "A potion that grants immunity to radiant damage for 1 hour.", price: "400 GP", availability: "Rare" },
            { name: "Shooting Star Charm", description: "Allows the user to make a wish once per month, with unpredictable results.", price: "3,000 GP", availability: "Legendary" },
            { name: "Moonstone Circlet", description: "Grants +2 to Wisdom saving throws while worn.", price: "1,000 GP", availability: "Rare" }
        ],
        specialOffers: "Discounts for Dreamers: 15% off for those who share a wish or dream with Lumina.",
        tradePolicy: "Accepts gold, star fragments, and rare celestial artifacts as payment.",
        personalityTraits: ["Ethereal", "Cryptic"],
        quirks: ["Often gazes up at the sky mid-conversation.", "Leaves faint trails of stardust in her wake."],
        catchphrases: ["The stars whisper secrets to those who listen.", "Each item holds a piece of the cosmos—treat it well."],
        disposition: "Calm and serene; patient with dreamers but dismissive of those who are overly skeptical or pragmatic.",
        hooks: {
            rumors: "It's said Lumina's goods are gifts from a celestial being she once saved.",
            sideQuest: "Recover a missing Starfall Gem stolen by a shadowy thief.",
            hiddenMotive: "Lumina is a guardian of the celestial planes, subtly influencing mortal realms to protect the balance."
        },
        token: "images/token/token3.png",
        shopDescription: "A celestial-themed stall adorned with glowing star motifs, shimmering fabrics, and an enchanted canopy that resembles a starry sky. The air around it feels cooler and hums with faint celestial energy.",
        rulesOfTrade: "No refunds; the stars' gifts are eternal and non-negotiable.",
        hours: "Appears at twilight and vanishes before dawn.",
        uniqueSellingPoint: "Lumina specializes in celestial and star-themed magical artifacts, each shimmering with the light of the cosmos."
    },
    {
        id: 4,
        name: "Rorkell 'Firemane' Ashbrand",
        offerings: [
            { name: "Phoenix Feather Arrows", description: "Arrows that ignite on impact, dealing an additional 1d6 fire damage.", price: "150 GP per bundle of 5", availability: "Uncommon" },
            { name: "Infernal Lantern", description: "Sheds light in any magical darkness within a 30-foot radius.", price: "500 GP", availability: "Rare" },
            { name: "Eruption Rod", description: "Once per day, creates a 15-foot cone of fire (4d6 fire damage, DC 15 Dex save for half).", price: "1,200 GP", availability: "Rare" },
            { name: "Flameburst Flask", description: "A throwable flask that explodes in a 10-foot radius, dealing 2d6 fire damage.", price: "100 GP each", availability: "Common" },
            { name: "Cloak of Embers", description: "Grants resistance to fire damage and creates harmless sparks when in motion.", price: "900 GP", availability: "Very Rare" },
            { name: "Blazing Blade", description: "A longsword that can ignite on command, adding 1d8 fire damage to its attacks.", price: "1,500 GP", availability: "Very Rare" },
            { name: "Inferno Bomb", description: "A one-time-use explosive that creates a 20-foot-radius fireball (6d6 fire damage, DC 15 Dex save for half).", price: "1,000 GP", availability: "Rare" },
            { name: "Firestarter Gloves", description: "Grants the ability to cast the *Produce Flame* cantrip at will.", price: "300 GP", availability: "Uncommon" },
            { name: "Molten Core Shield", description: "A shield that absorbs heat, granting +2 AC and resistance to fire damage.", price: "1,100 GP", availability: "Very Rare" },
            { name: "Scorched Earth Boots", description: "Leave a trail of fire behind you; creatures entering the trail take 1d4 fire damage.", price: "600 GP", availability: "Rare" },
            { name: "Ashen Amulet", description: "Grants immunity to environmental fire hazards.", price: "750 GP", availability: "Rare" },
            { name: "Pyrocracker Wand", description: "Creates colorful, harmless explosions for festive displays or distractions.", price: "250 GP", availability: "Common" },
            { name: "Firemane's Flask", description: "A magical flask that can produce up to 1 gallon of boiling water per day.", price: "200 GP", availability: "Uncommon" },
            { name: "Charcoal Pendant", description: "Once per day, grants advantage on saving throws against fire-based spells or effects.", price: "400 GP", availability: "Uncommon" },
            { name: "Searing Spear", description: "A spear that deals an extra 1d6 fire damage and causes minor burns (disadvantage on Concentration checks).", price: "1,000 GP", availability: "Rare" },
            { name: "Burning Heart Gem", description: "A gem that can be consumed to cast *Fireball* once (level 3).", price: "500 GP", availability: "Rare" },
            { name: "Lava Lamp Orb", description: "A magical orb that provides dim light and radiates comforting warmth.", price: "150 GP", availability: "Common" },
            { name: "Flamebound Tome", description: "A spellbook resistant to fire damage, with embossed flame designs.", price: "300 GP", availability: "Uncommon" },
            { name: "Kindling Cube", description: "A small magical cube that can ignite campfires instantly.", price: "50 GP", availability: "Common" },
            { name: "Volcanic Stone Bracers", description: "Grants the wearer +1 Strength and resistance to fire damage.", price: "1,200 GP", availability: "Very Rare" }
        ],
        specialOffers: "Explosive Deals: Buy three Flameburst Flasks, get a fourth free.",
        tradePolicy: "Accepts gold, rare minerals, or heat-resistant materials as payment.",
        personalityTraits: ["Boisterous", "Reckless"],
        quirks: ["Laughs maniacally while demonstrating dangerous items.", "His horns are perpetually scorched from his experiments."],
        catchphrases: ["Let's turn up the heat!", "You'll be the center of attention—and destruction!"],
        disposition: "Enthusiastic and welcoming to thrill-seekers, but dismissive of cautious or overly practical customers.",
        hooks: {
            rumors: "Some say Rorkell once survived an eruption by riding a wave of molten lava.",
            sideQuest: "Retrieve a rare Ember Gem from a volcanic dungeon for Rorkell to create his ultimate explosive.",
            hiddenMotive: "Rorkell seeks to ignite the dormant volcano near his homeland to awaken ancient fire spirits."
        },
        token: "images/token/token4.png",
        shopDescription: "A fiery stall surrounded by harmless crackling embers and glowing coals. The air smells of sulfur and burning wood, and Rorkell's tools and wares gleam with a faint, fiery glow.",
        rulesOfTrade: "No refunds; if it explodes, you know it worked.",
        hours: "Open from midday until the last ember fades at night.",
        uniqueSellingPoint: "Rorkell specializes in fire and heat-based enchanted items, perfect for adventurers who crave a little spark in their battles."
    },
    {
        id: 5,
        name: "Selara Moonvine",
        offerings: [
            { name: "Everbloom Seedlings", description: "Instantly grow into cover or obstacles when planted, providing strategic advantages in combat.", price: "300 GP each", availability: "Uncommon" },
            { name: "Dewdrop Amulet", description: "Restores 1d4 hit points per hour when the wearer is near a source of natural water.", price: "500 GP", availability: "Rare" },
            { name: "Thorned Vine Lash", description: "A living whip that deals 1d8 slashing damage and can restrain enemies (DC 14 Strength save).", price: "700 GP", availability: "Rare" },
            { name: "Blooming Tea Leaves", description: "When brewed, provides resistance to poison and heals 1d6 hit points.", price: "100 GP per pouch", availability: "Common" },
            { name: "Glowleaf Lantern", description: "A lantern made from enchanted leaves that provides bright light in a 30-foot radius and dim light for an additional 30 feet.", price: "250 GP", availability: "Uncommon" },
            { name: "Healing Sap Vial", description: "Restores 2d4+2 hit points when consumed.", price: "50 GP each", availability: "Common" },
            { name: "Moonlit Blossom", description: "A magical flower that glows softly at night and grants advantage on Wisdom (Perception) checks in darkness.", price: "350 GP", availability: "Rare" },
            { name: "Entangling Roots Charm", description: "Once per day, cast *Entangle* as a bonus action.", price: "600 GP", availability: "Rare" },
            { name: "Oakheart Shield", description: "A wooden shield that provides +2 AC and resistance to bludgeoning damage.", price: "1,200 GP", availability: "Very Rare" },
            { name: "Lifebloom Potion", description: "Restores 4d4+4 hit points and cures one condition (poisoned, blinded, or paralyzed).", price: "200 GP", availability: "Uncommon" },
            { name: "Verdant Cloak", description: "A cloak made of enchanted moss that grants the wearer advantage on Stealth checks in natural environments.", price: "800 GP", availability: "Rare" },
            { name: "Sporecloud Pouch", description: "A pouch that releases a 10-foot-radius cloud of spores, causing creatures to make a DC 14 Constitution save or be blinded for 1 minute.", price: "400 GP", availability: "Uncommon" },
            { name: "Enchanted Acorn", description: "Transforms into a fully grown tree over the course of 1 hour when planted.", price: "300 GP", availability: "Uncommon" },
            { name: "Forestwarden's Circlet", description: "Grants the ability to communicate with plants and animals once per day.", price: "1,000 GP", availability: "Very Rare" },
            { name: "Petalburst Powder", description: "A throwable powder that creates a burst of petals, obscuring vision in a 15-foot radius for 1 minute.", price: "150 GP", availability: "Common" },
            { name: "Thornskin Balm", description: "When applied, grants the user resistance to piercing damage for 1 hour.", price: "200 GP", availability: "Uncommon" },
            { name: "Vinewoven Bracers", description: "Bracers that grant +1 to AC and allow the wearer to cast *Thorn Whip* once per day.", price: "900 GP", availability: "Very Rare" },
            { name: "Sunflower Shield", description: "A shield that reflects sunlight, dealing 1d6 radiant damage to attackers on a successful block.", price: "1,100 GP", availability: "Rare" },
            { name: "Wildroot Tonic", description: "Increases Strength by 2 for 1 hour, but causes the user to sprout temporary vines.", price: "250 GP", availability: "Uncommon" },
            { name: "Bramble Ring", description: "Once per day, creates a barrier of thorns around the wearer (10-foot radius, 2d6 piercing damage to creatures passing through).", price: "1,500 GP", availability: "Very Rare" }
        ],
        specialOffers: "Nature's Gift: Bring her a rare plant specimen, and she'll offer a 20% discount on your next purchase.",
        tradePolicy: "Accepts gold, rare seeds, and naturally magical materials as payment.",
        personalityTraits: ["Gentle", "Passionate"],
        quirks: ["Hums soothing melodies to her plants.", "Her flowers seem to bloom or wilt in response to her emotions."],
        catchphrases: ["Nature provides for those who respect her.", "Every leaf holds a story."],
        disposition: "Warm and welcoming, but quietly disapproving of those who harm nature or misuse her wares.",
        hooks: {
            rumors: "It's said Selara once revived an entire forest after a devastating wildfire.",
            sideQuest: "Gather Moonshadow Petals from a haunted grove to help Selara create a powerful new potion.",
            hiddenMotive: "Selara guards an ancient druidic secret that she fears could be misused by others."
        },
        token: "images/token/token5.png",
        shopDescription: "A tranquil stall entwined with glowing vines and blooming flowers, exuding a calming floral scent. The soft hum of nature magic fills the air, and Selara's wares seem to pulse faintly with life.",
        rulesOfTrade: "No harm shall come to nature through the use of her goods.",
        hours: "Open from sunrise to sunset.",
        uniqueSellingPoint: "Selara specializes in herbalist potions, enchanted plants, and nature-based magic items, perfect for those who walk in harmony with the natural world."
    },
    {
        id: 6,
        name: "Thornax the Collector",
        offerings: [
            { name: "Mirror of Whispers", description: "Reveals secrets about anyone reflected, but exacts a small toll on the user's sanity.", price: "600 GP", availability: "Rare" },
            { name: "Ring of Echoing Souls", description: "Allows communication with spirits for guidance, but whispers persist even after removal.", price: "750 GP", availability: "Very Rare" },
            { name: "Shadowmantle Cloak", description: "Grants advantage on Stealth checks, but causes occasional paranoia (DM discretion).", price: "900 GP", availability: "Rare" },
            { name: "Cursed Coin", description: "Brings incredible luck for 24 hours, after which misfortune follows for 24 hours.", price: "300 GP", availability: "Uncommon" },
            { name: "Phantom's Locket", description: "Allows the user to go incorporeal for 1 minute, once per day. The locket grows colder with each use.", price: "1,200 GP", availability: "Very Rare" },
            { name: "Ethereal Grimoire", description: "Contains one random dark spell, but requires a small sacrifice of HP to cast.", price: "1,000 GP", availability: "Rare" },
            { name: "Veil of Forgotten Names", description: "Conceals the wearer's identity completely, but drains 1 Charisma point while worn.", price: "500 GP", availability: "Uncommon" },
            { name: "Shard of Black Ice", description: "Once per day, creates a field of black ice in a 10-foot radius, causing creatures to slip (Dex save DC 15).", price: "450 GP", availability: "Rare" },
            { name: "Specter's Amulet", description: "Summons a spectral guardian for 1 minute to protect the wearer, but decreases max HP by 5 temporarily.", price: "700 GP", availability: "Rare" },
            { name: "Wicked Tarot Deck", description: "Draw a card for unpredictable results, ranging from a boon to a curse.", price: "800 GP", availability: "Rare" },
            { name: "Lantern of Shadows", description: "Sheds a dim, eerie light in a 60-foot radius and reveals invisible creatures in the area.", price: "550 GP", availability: "Rare" },
            { name: "Blood-etched Dagger", description: "A cursed dagger that deals 1d6 necrotic damage but binds to the wielder until a curse is lifted.", price: "400 GP", availability: "Uncommon" },
            { name: "Haunted Hourglass", description: "Once per day, reverse time by 6 seconds, but causes a haunting dream that night.", price: "1,500 GP", availability: "Very Rare" },
            { name: "Raven's Eye Pendant", description: "Grants advantage on Insight checks but attracts the attention of dark entities.", price: "450 GP", availability: "Uncommon" },
            { name: "Book of Endless Lies", description: "A tome that grants knowledge but distorts truths in unpredictable ways.", price: "600 GP", availability: "Rare" },
            { name: "Curio of the Forgotten", description: "Once per day, erases 1 minute of memory for a creature of your choice.", price: "1,000 GP", availability: "Very Rare" },
            { name: "Nightmare Flask", description: "Unleashes a cloud of fear (DC 16 Wisdom save) in a 15-foot radius. Single use.", price: "300 GP", availability: "Uncommon" },
            { name: "Soulbound Key", description: "Opens any mundane lock but binds itself to the user's soul, inflicting 1 HP damage each use.", price: "700 GP", availability: "Rare" },
            { name: "Ashen Crown", description: "Grants resistance to fire damage, but the wearer is constantly surrounded by an unsettling smoky aura.", price: "1,200 GP", availability: "Very Rare" },
            { name: "Eclipse Cloak", description: "Once per long rest, shrouds the user in total darkness for 1 minute, granting immunity to detection.", price: "2,000 GP", availability: "Legendary" }
        ],
        specialOffers: "Temptation of the Damned: Thornax offers one random cursed item at half price to anyone willing to sign a mysterious pact.",
        tradePolicy: "Accepts gold, cursed artifacts, and rare occult items. Refuses to deal with clerics or paladins.",
        personalityTraits: ["Sinister", "Charming"],
        quirks: ["Often appears suddenly and unannounced.", "Casts unsettling glances that feel like they're reading your soul."],
        catchphrases: ["Every curse is but a challenge waiting to be mastered.", "Dare to take destiny into your own hands?"],
        disposition: "Clever and persuasive, but with a malevolent edge. Willing to exploit weakness in others for gain.",
        hooks: {
            rumors: "It's said that Thornax was once a noble, cursed into his current form by an ancient relic he could not resist.",
            sideQuest: "Retrieve the cursed mask of Malrik from a crypt to complete Thornax's 'personal collection.'",
            hiddenMotive: "Thornax seeks to collect cursed relics to piece together a powerful artifact and regain his lost humanity."
        },
        token: "images/token/token6.png",
        shopDescription: "A dark and shadowy stall draped in tattered black cloth. Strange symbols faintly glow on the surfaces of Thornax's wares, and the air is heavy with an unidentifiable tension.",
        rulesOfTrade: "All sales are final. Wares are sold 'as-is,' with no responsibility for curses incurred.",
        hours: "Appears only at night and vanishes before dawn.",
        uniqueSellingPoint: "Thornax specializes in rare cursed relics and items that offer great power at a cost, catering to those who thrive on danger and mystery."
    },
    {
        id: 7,
        name: "Fizzwick Wobblegear",
        offerings: [
            { name: "Wand of Wonder-lite", description: "A discount version of the Wand of Wonder, producing random magical effects with slightly higher chaos.", price: "150 GP", availability: "Uncommon" },
            { name: "Sparking Staff", description: "A staff that casts Lightning Bolt, but occasionally zaps the wielder (1d4 damage).", price: "300 GP", availability: "Rare" },
            { name: "Glitching Cloak", description: "Grants invisibility for 1 minute, but may flicker and reveal the wearer briefly.", price: "250 GP", availability: "Uncommon" },
            { name: "Potion of Unpredictable Strength", description: "Grants +2 Strength for 1 hour, but a random stat is temporarily reduced by 2.", price: "75 GP", availability: "Common" },
            { name: "Booming Boots", description: "Doubles jumping distance, but landing creates a loud thunderclap.", price: "200 GP", availability: "Uncommon" },
            { name: "Capricious Compass", description: "Points to treasure—or danger—with a 50/50 chance.", price: "100 GP", availability: "Common" },
            { name: "Jittering Gauntlets", description: "Grants +1 to melee attack rolls, but causes minor tremors in the hands when idle.", price: "180 GP", availability: "Uncommon" },
            { name: "Bag of Mild Tricks", description: "A budget version of the Bag of Tricks; summons mildly useful animals (e.g., a goat or squirrel).", price: "120 GP", availability: "Uncommon" },
            { name: "Whimsical Hat", description: "Allows minor illusion once per short rest, but may randomly change color or shape.", price: "80 GP", availability: "Common" },
            { name: "Fizzwick's Flame Grenade", description: "Deals 2d6 fire damage in a 10-foot radius, but may misfire and only ignite with a puff of smoke.", price: "100 GP", availability: "Uncommon" },
            { name: "Clockwork Mouse Familiar", description: "A mechanical mouse that acts as a familiar but occasionally malfunctions and scurries off randomly.", price: "150 GP", availability: "Uncommon" },
            { name: "Potion of Almost-Healing", description: "Heals 2d4+2 HP, but has a 10% chance of causing a minor rash.", price: "50 GP", availability: "Common" },
            { name: "Scroll of Misaligned Fireball", description: "Casts Fireball, but its center point may drift by up to 5 feet in a random direction.", price: "200 GP", availability: "Rare" },
            { name: "Shield of Startling Reflection", description: "Grants +1 AC, but occasionally reflects a distorted image of the wielder.", price: "300 GP", availability: "Rare" },
            { name: "Unstable Teleportation Ring", description: "Allows teleportation up to 30 feet, but the user may appear facing the wrong direction.", price: "500 GP", availability: "Rare" },
            { name: "Fizzwick's Bubble Blower", description: "Produces large, colorful bubbles that pop with a small magical burst (1d6 force damage).", price: "75 GP", availability: "Common" },
            { name: "Confounding Lantern", description: "Emits light in a 30-foot radius, but occasionally flickers and emits strange shadows.", price: "90 GP", availability: "Common" },
            { name: "Patchwork Potion", description: "Grants resistance to a random damage type for 1 hour.", price: "100 GP", availability: "Uncommon" },
            { name: "Mishap Medallion", description: "Grants advantage on one saving throw per day, but causes a harmless magical mishap afterward.", price: "200 GP", availability: "Uncommon" },
            { name: "Fizzwick's Rocket Shoes", description: "Grants a 60-foot dash as a bonus action, but may cause the wearer to stumble and fall prone (Dex save DC 10).", price: "250 GP", availability: "Rare" }
        ],
        specialOffers: "Bundle of Chaos: Buy three items, get a random magical trinket free!",
        tradePolicy: "Accepts gold, gemstones, and experimental magical components. Offers a 10% discount for amusing stories or jokes.",
        personalityTraits: ["Eccentric", "Optimistic"],
        quirks: ["Wagon constantly emits sparks and puffs of smoke.", "Fizzwick's speech is often interrupted by giggles and bursts of inspiration."],
        catchphrases: ["Why spend a fortune on perfection when you can have budget-friendly brilliance?", "What's the worst that could happen?"],
        disposition: "Friendly and excitable, with a tendency to oversell the stability of his items.",
        hooks: {
            rumors: "Some say Fizzwick's wagon was enchanted by a mad mage, making it both his home and his curse.",
            sideQuest: "Help Fizzwick retrieve a lost blueprint for a 'perpetual motion gear' from a rival gnome.",
            hiddenMotive: "Fizzwick secretly hopes to build a magical invention that will grant him eternal recognition in the gnomish inventor community."
        },
        token: "images/token/token7.png",
        shopDescription: "A ramshackle wagon brimming with trinkets and gadgets, its wooden sides painted with peeling bright colors. Small bursts of magical sparks fly off constantly, and a cheerful sign reads: 'Fizzwick’s Magical Bargains – Slightly Unpredictable!'",
        rulesOfTrade: "No guarantees or warranties; all items are sold 'as-is.'",
        hours: "Appears in bustling markets at midday, vanishes before sunset.",
        uniqueSellingPoint: "Fizzwick specializes in affordable magical items with quirks, making them perfect for adventurous buyers with a sense of humor."
    },
    {
        id: 8,
        name: "Santiago 'Silverstache' Velasco",
        offerings: [
            { name: "Stormcaller's Cutlass", description: "A finely crafted cutlass that crackles with electricity, dealing an extra 1d6 lightning damage on a hit.", price: "750 GP", availability: "Rare" },
            { name: "Flintlock of the Siren's Kiss", description: "A magical pistol that emits a haunting melody when fired; once per day, the shot can charm a target (DC 14).", price: "900 GP", availability: "Very Rare" },
            { name: "Barnacle Buckler", description: "A small but sturdy buckler encrusted with magical barnacles, granting resistance to bludgeoning damage.", price: "500 GP", availability: "Rare" },
            { name: "The Phantom's Hook", description: "An enchanted grappling hook that pulls the user to any surface within 30 feet as a bonus action.", price: "600 GP", availability: "Rare" },
            { name: "Boots of the Tidemaster", description: "Allows the wearer to walk on water and gain advantage on Athletics checks while swimming.", price: "1,200 GP", availability: "Very Rare" },
            { name: "Santiago's Silver Shot", description: "A pouch of 10 bullets that ignore resistance to nonmagical ammunition.", price: "300 GP", availability: "Uncommon" },
            { name: "Whispering Spyglass", description: "A spyglass that lets the user hear whispers from up to 300 feet away when focused on a target.", price: "400 GP", availability: "Uncommon" },
            { name: "Corsair's Gambit", description: "A deck of enchanted playing cards that can be thrown as ranged weapons, dealing 1d8 slashing damage.", price: "250 GP", availability: "Uncommon" },
            { name: "Tidecaller's Tricorn", description: "A stylish tricorn hat that grants the ability to control small bodies of water at will.", price: "800 GP", availability: "Rare" },
            { name: "Powderhorn of the Tempest", description: "Gunpowder stored in this horn is immune to dampening effects and deals an additional 1d6 thunder damage when used.", price: "350 GP", availability: "Uncommon" },
            { name: "Siren's Locket", description: "A pendant that lets the wearer breathe underwater for up to 10 minutes per day.", price: "500 GP", availability: "Rare" },
            { name: "Jolly Roger's Pact", description: "A cursed black flag that can summon a spectral crew for 1 minute, aiding in combat or sailing.", price: "2,000 GP", availability: "Legendary" },
            { name: "Cutlass of the Depths", description: "A blade that deals an extra 1d6 cold damage and leaves foes with a lingering chill.", price: "700 GP", availability: "Rare" },
            { name: "Brine-soaked Vest", description: "A vest that grants resistance to poison damage and immunity to ingested toxins.", price: "600 GP", availability: "Rare" },
            { name: "Compass of the Forsaken", description: "Always points to the nearest hidden treasure, but at a cost—the user dreams of eerie voices.", price: "750 GP", availability: "Rare" },
            { name: "Echoing Pistol", description: "A pistol that fires two shots in quick succession, the second being a spectral duplicate of the first.", price: "900 GP", availability: "Very Rare" },
            { name: "The Golden Doubloon", description: "A single enchanted coin that, when flipped, can grant advantage or disadvantage on one roll (once per long rest).", price: "250 GP", availability: "Uncommon" },
            { name: "Sea Witch's Grimoire", description: "A book of nautical spells and curses, allowing access to one additional spell slot per day.", price: "1,500 GP", availability: "Very Rare" },
            { name: "Gilded Captain's Coat", description: "A flamboyant, gold-trimmed coat that grants +2 Charisma when worn.", price: "1,000 GP", availability: "Rare" },
            { name: "Cannonball of the Damned", description: "A blackened cannonball that, when fired, bursts into ghostly flames, dealing 4d10 necrotic damage.", price: "2,500 GP", availability: "Legendary" }
        ],
        specialOffers: "Pirate's Discount: 10% off for anyone who can beat Santiago in a game of chance.",
        tradePolicy: "Accepts gold, rare gems, and artifacts retrieved from shipwrecks. Offers additional discounts for sharing tales of legendary treasure hunts.",
        personalityTraits: ["Flamboyant", "Charming"],
        quirks: ["Often spins his pistols dramatically before holstering them.", "Tells a different version of the same story every time."],
        catchphrases: ["A weapon's only as good as the hands that wield it!", "Every item here has a legend—what story will you write with it?"],
        disposition: "Charismatic and theatrical, loves to entertain but becomes serious when discussing his wares.",
        hooks: {
            rumors: "It's said that Santiago once tricked a sea god out of a treasure chest—though no one knows how.",
            sideQuest: "Retrieve an ancient, rusted key from a sunken wreck to unlock a chest Santiago refuses to sell—unless he gets a share of the contents.",
            hiddenMotive: "Santiago is searching for a legendary lost ship said to carry an item that will make him 'the greatest pirate merchant of all time.'"
        },
        token: "images/token/token8.png",
        shopDescription: "A stall built from the remains of a shipwreck, with a mast proudly displaying Santiago’s personal flag. The air smells of salt and gunpowder, and every item gleams as though freshly polished. A small parrot perches nearby, occasionally squawking out half-finished sea shanties.",
        rulesOfTrade: "No refunds, no exchanges—only the sea decides if an item is truly meant for you.",
        hours: "Sets up near ports and seaside taverns in the evening, vanishes by dawn.",
        uniqueSellingPoint: "Santiago specializes in pirate-themed weapons, enchanted firearms, and seafaring relics."
    },
    {
        id: 9,
        name: "Emil Hawthorne",
        offerings: [
            { name: "Wand of Minor Wonders", description: "A simple wand that produces harmless magical effects at random.", price: "50 GP", availability: "Common" },
            { name: "Potion of Misdirection", description: "Makes the drinker briefly appear as someone else to onlookers.", price: "200 GP", availability: "Uncommon" },
            { name: "Bag of Endless Rations", description: "Produces simple but edible food once per day.", price: "400 GP", availability: "Rare" },
            { name: "Candle of Safe Rest", description: "Prevents nightmares and grants a full night’s rest when lit.", price: "150 GP", availability: "Common" },
            { name: "Boots of Quickstep", description: "Increase movement speed by 10 feet for 10 minutes per use (3 charges).", price: "500 GP", availability: "Uncommon" },
            { name: "Rogue’s Lucky Coin", description: "Once per day, grants advantage on a Dexterity saving throw.", price: "300 GP", availability: "Rare" },
            { name: "Lantern of Revealing", description: "Illuminates invisible creatures and objects within 30 feet.", price: "600 GP", availability: "Rare" },
            { name: "Ring of Whispering Echoes", description: "Allows silent communication with another ring wearer within 1 mile.", price: "700 GP", availability: "Rare" },
            { name: "Traveler’s Compass", description: "Always points toward the nearest town or settlement.", price: "250 GP", availability: "Uncommon" },
            { name: "Scroll of Identify", description: "Reveals the properties of an unknown magical item.", price: "150 GP", availability: "Common" },
            { name: "Alchemist’s Fire (Mislabelled)", description: "Flammable substance—Emil accidentally calls it 'Potion of Warmth'.", price: "100 GP", availability: "Uncommon" },
            { name: "Tome of Forgotten Tales", description: "A mysterious book that sometimes writes new stories overnight.", price: "900 GP", availability: "Rare" },
            { name: "Cloak of Inconspicuousness", description: "Makes the wearer blend into a crowd, but not completely invisible.", price: "750 GP", availability: "Rare" },
            { name: "Feather Token: Bird", description: "Summons a small magical bird that can deliver a short message.", price: "200 GP", availability: "Uncommon" },
            { name: "Emil’s Mystery Box", description: "An unidentified item at a bargain price. Could be anything!", price: "Varies", availability: "??? " },
            { name: "Potion of Questionable Strength", description: "Grants +1 to Strength for an hour, but also makes the drinker clumsy.", price: "180 GP", availability: "Uncommon" },
            { name: "Key of Many Doors", description: "Unlocks non-magical doors, but sometimes locks them instead.", price: "500 GP", availability: "Rare" },
            { name: "Amulet of Nervous Protection", description: "Emil swears it wards off danger. It doesn’t… but it is a nice trinket.", price: "50 GP", availability: "Common" },
            { name: "Shield of the Absentminded", description: "Provides +2 AC but occasionally 'forgets' to activate.", price: "800 GP", availability: "Rare" },
            { name: "Watchful Owl Figurine", description: "Comes to life at night and hoots if someone sneaks too close.", price: "600 GP", availability: "Rare" }
        ],
        specialOffers: "Haphazard Sales: Prices fluctuate daily—sometimes a great deal, sometimes not!",
        tradePolicy: "Accepts gold, but might also trade for information about Aldric Vaelor’s whereabouts.",
        personalityTraits: ["Eager", "Nervous"],
        quirks: ["Accidentally mislabels items.", "Talks to himself when making decisions."],
        catchphrases: ["Uh... I think this is a fair price?", "Y-you’re sure you want that one?"],
        disposition: "Well-meaning but inexperienced, Emil is desperate to keep the shop running and earn respect.",
        hooks: {
            rumors: "Some say Aldric was last seen meeting with a cloaked figure in the dead of night.",
            sideQuest: "Help Emil investigate his missing master by tracking down Aldric’s last known associates.",
            hiddenMotive: "Emil is afraid to admit that some of the stock is beyond his understanding—and possibly dangerous."
        },
        token: "images/token9.png",
        shopDescription: "A cluttered but cozy magic shop filled with shelves of potions, trinkets, and odd magical items. Some items are clearly valuable, while others seem misplaced or mislabeled. A faint layer of dust covers stock Emil is too afraid to touch.",
        rulesOfTrade: "No refunds—mostly because Emil doesn’t know how to process them.",
        hours: "Open most of the time, though Emil sometimes forgets to flip the sign.",
        uniqueSellingPoint: "A mix of practical adventuring goods and unpredictable magical curiosities—some at unbeatable prices!"
    }
    
    
];
